name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build image
        run: docker build -t udm-rasterise-proximity .

      - name: test
        run: docker run -v $PWD/data:/data --env LAYER_NAME=output --env SQUARED=True udm-rasterise-proximity

      - name: test extent
        run: docker run -v $PWD/data:/data --env EXTENT=218000,600000,313000,691000 --env LAYER_NAME=output --env SQUARED=True udm-rasterise-proximity

      - name: Archive test output
        uses: actions/upload-artifact@v2
        with:
          name: udm-rasterise-proximity
          path: data/outputs/proximity.tif
